### ISSUE TITLE
MAE diag outdated

### ISSUE THREAD

**Issue by williamstanner** [lichfiet/sqlLibrary#31]
EVO-33866 Scheduled Not Valid for A/R Customerid XXXXX Misc Receipt | T1 Preapproved

^ outputs in the MAE diagnostic.

The Misc recipt version of EVO-33866 is no longer a T1 preapproved.

"
END || CASE 
WHEN miscinvnonarmop.businessactionid IS NOT NULL
THEN 'EVO-33866 Scheduled Not Valid for A/R Customerid XXXXX Misc Receipt | T2'
		ELSE ''

"

**Comment by lichfiet** [comment]
changed verbage, sql updated
