### ISSUE TITLE
Reservation availability script misses a scenario.

### ISSUE THREAD

**Issue by williamstanner** [lichfiet/sqlLibrary#39]
Just had a call come in about a conflict that was missed by the diagnostic.

If one reservation is older than another but the newer one is closed and the older one has payments that have been made on it that are newer than the start date of the the closed reservation, that is a conflict that does not pull on the diag.

As an example if you pull CID 103976 for 12/20/2023 or before and look for reservation stopping 336, conflicting is 327.

The workaround for this issue is transferring the item that the oldest reservation is on.

**Comment by lichfiet** [comment]
resolved this in a commit from less than a month ago
