### ISSUE TITLE
EVO-3087 false positive on MAE diag (Truely EVO-30821)

### ISSUE THREAD

**Issue by williamstanner** [lichfiet/sqlLibrary#41]
Getting (EVO-3087 Scheduled Account XXXX Not Valid for A/R Customerid XXXXX Sales Deal | T1 Front End Fix, See CR for infoEVO-31125 Sales Deal OOB Method of Payment != Balance to Finance | T1 Preapproved)

When the error message is "A/P Scheduled Account 33700 is not the proper AP Account for VendorID:..."

The Tier 1 resolution does not resolve.

**Comment by lichfiet** [comment]
added `'EVO-3087 Scheduled Account XXXX Not Valid for A/R Customerid XXXXX Sales Deal | T1 Front End Fix, See CR for info. May be EVO-30821 but not likely'` until we can test another instance of this
