### ISSUE TITLE
Not cool enough, cannot recreate management activity document with SQL.

### ISSUE THREAD

**Issue by williamstanner** [lichfiet/sqlLibrary#45]
SELECT 22812,
	left(bai.dtstamp::VARCHAR, 9) AS dtstamp,
	coa.acctdept AS accountnumber,
	ROUND(debitamt * .0001, 2) AS debitamt,
	ROUND(creditamt * .0001, 2) AS creditamt,
	description || ' - Reversal' AS description1,
	0 AS description2,
	'reverse entry' AS ref1,
	0 AS ref2,
	storeid
FROM mabusinessactionitem bai
INNER JOIN glchartofaccounts coa ON coa.acctdeptid = bai.accountid
WHERE bai.businessactionid = 796757414895003820

**Comment by lichfiet** [comment]
updated https://github.com/lichfiet/sqlLibrary/edit/main/tools/jeReversal.sql, added

```sql
SELECT ba.documentnumber,
	left(bai.dtstamp::VARCHAR, 9) AS dtstamp,
	coa.acctdept AS accountnumber,
	ROUND(debitamt * .0001, 2) AS debitamt,
	ROUND(creditamt * .0001, 2) AS creditamt,
	description || ' - Reversal' AS description1,
	0 AS description2,
	'reverse entry' AS ref1,
	0 AS ref2,
	ba.storeid
FROM mabusinessactionitem bai
INNER JOIN glchartofaccounts coa ON coa.acctdeptid = bai.accountid
INNER JOIN mabusinessaction ba ON ba.businessactionid = bai.businessactionid
WHERE ba.STATUS != 1
	AND ba.documentnumber = 'DOCUMENT NUMBER'

```
